APPLICATION = embed-io

RIOTBASE ?= $(PWD)/../../../../RIOT

BOARD ?= samr21-xpro


export ELFFILE=$(PWD)/build/bin/embed-io
export HEXFILE=$(PWD)/build/bin/embed-io.hex

include $(RIOTBASE)/Makefile.include

all:
	@$(OBJCOPY) -O ihex $(ELFFILE) $(HEXFILE)
